version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    image: frontend-app
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: backend-app
    container_name: backend
    ports:
      - "5050:5050"
    restart: unless-stopped
